### PR TITLE
fix: Removed data lookup for azurerm_resource_group, so that the reso…

### LINKED ISSUE #68: tf plan fails if resource group is created outside of the module
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.9.6

### Module Version

0.3.0

### AzureRM Provider Version

3.116.0

### Affected Resource(s)/Data Source(s)

azurerm_resource_group

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
  location = "uksouth"
  name     = "test-rg"
}

module "alz_management" {
  source  = "Azure/avm-ptn-alz-management/azurerm"
  version = "0.3.0"

  automation_account_name         = "test-aa"
  location                        = "uksouth"
  log_analytics_workspace_name    = "test-log"
  resource_group_name             = azurerm_resource_group.rg.name
  resource_group_creation_enabled = false
}
```

### tfvars variables values

```hcl
NA
```

### Debug Output/Panic Output

```shell
Error: Error: Resource Group "test-rg" was not found

  with module.alz_management.data.azurerm_resource_group.management[0],
  on .terraform\modules\alz_management\main.tf line 10, in data "azurerm_resource_group" "management":
  10: data "azurerm_resource_group" "management" {

2024-10-01T15:26:58.798+0100 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2024-10-01T15:26:58.829+0100 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2024-10-01T15:26:58.832+0100 [INFO]  provider: plugin process exited: plugin=.terraform/providers/registry.terraform.io/azure/azapi/2.0.0-beta/windows_amd64/terraform-provider-azapi_v2.0.0-beta.exe id=19156
2024-10-01T15:26:58.832+0100 [DEBUG] provider: plugin exited
2024-10-01T15:26:58.906+0100 [INFO]  provider: plugin process exited: plugin=.terraform/providers/registry.terraform.io/hashicorp/azurerm/3.116.0/windows_amd64/terraform-provider-azurerm_v3.116.0_x5.exe id=17356
2024-10-01T15:26:58.909+0100 [DEBUG] provider: plugin exited
```

### Expected Behaviour

terraform should successfully create the plan

### Actual Behaviour

terraform fails to create the plan, because the resource group is expected to exist, but is going to be created as part of the plan.

To resolve i think, just remove the data objectfor the azurerm_resource_group resource, and update the local variables to reference the variable "resource_group_name"

### Steps to Reproduce

terraform apply

### Important Factoids

_No response_

### References

_No response_

### PR DESCRIPTION
**Pull request by paul-e-martin**
…urce group can be created external to this module, but part of the same plan

## Description
Removed the data lookup for the resource group, as this expected the resource group to already exist in the environment, and didn't allow for it to be created outside of the module within the same plan.
Updated the locals to use the resource_group_name variable if resource_group_creation_enabled is false, and to use the azapi::build_resource_id function to generate the resource_group_resource_id.
Added data.tf with the azapi_client_config data entry.

Fixes #68
Closes #68

## Type of Change

- [ ] Non-module change (e.g. CI/CD, documentation, etc.)
- [ x] Azure Verified Module updates:
  - [ x] Bugfix containing backwards compatible bug fixes
    - [x ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates.
  - [ ] Breaking changes.
  - [ ] Update to documentation

# Checklist

- [x ] I'm sure there are no other open Pull Requests for the same update/change
- [x ] My corresponding pipelines / checks run clean and green without any errors or warnings
- [ x] I did run all  [pre-commit](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/terraform-contribution-flow/#5-run-pre-commit-checks) checks

### CODE REVIEW

**Comment by paul-e-martin** [comment]
Looks like the lint rules don't like "provider::azapi::build_resource_id", amended to build the resource id manually rather than using the function, and it works fine. Do you want me to resubmit the pull request with the resource id being manually created, or is the linting rule going to be looked at?

**Comment by matt-FFFFFF** [comment]
> Looks like the lint rules don't like "provider::azapi::build_resource_id", amended to build the resource id manually rather than using the function, and it works fine. Do you want me to resubmit the pull request with the resource id being manually created, or is the linting rule going to be looked at?

Thanks but no, we will update the linter

**Comment by matt-FFFFFF** [comment]
> > Looks like the lint rules don't like "provider::azapi::build_resource_id", amended to build the resource id manually rather than using the function, and it works fine. Do you want me to resubmit the pull request with the resource id being manually created, or is the linting rule going to be looked at?
> 
> Thanks but no, we will update the linter

Completed in Azure/tfmod-scaffold#75

**Comment by paul-e-martin** [comment]
ok, i had reverted to string interpolation. Just updating the fork again now.

**Comment by paul-e-martin** [comment]
> > > Looks like the lint rules don't like "provider::azapi::build_resource_id", amended to build the resource id manually rather than using the function, and it works fine. Do you want me to resubmit the pull request with the resource id being manually created, or is the linting rule going to be looked at?
> > 
> > 
> > Thanks but no, we will update the linter
> 
> Completed in [Azure/tfmod-scaffold#75](https://github.com/Azure/tfmod-scaffold/pull/75)

ok, i had reverted to string interpolation. Just updating the fork again now.

**Comment by paul-e-martin** [comment]
> > > > Looks like the lint rules don't like "provider::azapi::build_resource_id", amended to build the resource id manually rather than using the function, and it works fine. Do you want me to resubmit the pull request with the resource id being manually created, or is the linting rule going to be looked at?
> > > 
> > > 
> > > Thanks but no, we will update the linter
> > 
> > 
> > Completed in [Azure/tfmod-scaffold#75](https://github.com/Azure/tfmod-scaffold/pull/75)
> 
> ok, i had reverted to string interpolation. Just updating the fork again now.

ok,done

**Review by matt-FFFFFF — APPROVED** [review]

**Pull request merged**
